apiVersion: v2
name: keezy
description: Kubernetes Secret Management GUI
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - secrets
  - gui
  - management
home: https://github.com/makeugreat/keezy
sources:
  - https://github.com/makeugreat/keezy
maintainers:
  - name: makeugreat
