{{- if not .Values.session.existingSecret -}}
{{- $secretName := printf "%s-session" (include "keezy.fullname" .) -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "keezy.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and $existingSecret $existingSecret.data }}
  session-secret: {{ index $existingSecret.data "session-secret" }}
  {{- else if .Values.session.secret }}
  session-secret: {{ .Values.session.secret | b64enc }}
  {{- else }}
  session-secret: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
{{- end }}
